name: Python CI with Docker and Formatting Check

on:
  push:

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --recursive --in-place .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false